### ISSUE TITLE
cyclone.httpclient issue with SSL connections.

### ISSUE THREAD

**Issue by miverson** [fiorix/cyclone#160]
I'm experiencing an issue connecting to a backend service via SSL, using a self signed certificate. I'm using these library versions:

pypy 2.4.0
Twisted v14.0.2
cyclone v1.1

It appears, by default deep in twisted.web.client:

```
168             self.factory.setURL(url)
169 
170             if self.factory.scheme == b'https':
171                 from twisted.internet import ssl
172                 contextFactory = ssl.ClientContextFactory()
173                 reactor.connectSSL(nativeString(self.factory.host),
174                                    self.factory.port,
175                                    self.factory, contextFactory)
176             else:
177                 reactor.connectTCP(nativeString(self.factory.host),
178                                    self.factory.port,
179                                    self.factory)
```

The context factory, by default, will perform certificate checks according to the BrowserLikePolicyForHTTPS specification. However, there is no way to override this default policy.
As a result, connections were failing using a self signed certificate with a mismatched hostname. (At this point, I really don't know which check is causing the failure; I'm already deeper into the twisted source than I ever wanted to be.)

It is possible to specify a custom context factory to bypass the default certificate checks, by handing one to the Agent() constructor. For example, in cyclone.httpclient we can replace:

```
agent = Agent(reactor)
```

with something akin to:

```
agent = Agent(reactor,WebClientContextFactory())
```

to hand an alternate context factory to the agent to define the desired checks. 

I can see a couple possible enhancements:
- Add an overridable method to cyclone.httpclient, allowing a user definable context factory.
- add configuration parameters that would create an appropriate context factory based upon the desired settings.

Complicating things a bit is that it appear that twisted has two APIs for dealing with this issue. One is the deprecated ClientContextFactory approach, and the newer IPolicyForHTTP approach.

At this point, I don't have anything worth turning into a pull request, but I figured I'd raise the issue to see if there are any opinions on a solution.

**Comment by ldanielburr** [comment]
https://github.com/dreid/treq/pull/80 covers adding your own IPolicyForHTTPS provider to treq.

**Comment by dpnova** [comment]
@miverson did treq resolve this for you? It could be worth closing this ticket but leaving this conversation here for people who also have the same issue.

**Comment by ldanielburr** [comment]
For what it is worth, using the current release of treq, you can handle self-signed certs with something like this:

    import treq
    from twisted.internet import ssl
    from twisted.web import client

    class MyPolicyForHTTPS(client.BrowserLikePolicyForHTTPS):
        def creatorForNetloc(self, hostname, port):
            return ssl.optionsForClientTLS(
                hostname.decode('ascii'),
                trustRoot=ssl.Certificate.loadPEM("""YOUR SELF-SIGNED CERT HERE""")
            )
    
    agent = client.Agent(self.reactor, contextFactory=MyPolicyForHTTPS())
    d = treq.post(
        agent=agent,
        data=...,
        headers={...},
        url=...
    )

**Comment by dpnova** [comment]
I'm going to close this. I think it's nice for us to have our own http client for basic use, but if people want a more fully fledged client, treq is fast becoming the best way to do it.
