### ISSUE TITLE
Question: Why doesn't HTTPConnection derive from t.w.h.HTTPChannel instead of t.p.b.LineReceiver?

### ISSUE THREAD

**Issue by mbogosian** [fiorix/cyclone#167]
This might be a stupid question, and I haven't looked too closely at comparing the code, but I'm curious why it was decided that [`cyclone.httpserver.HTTPConnection`](https://github.com/fiorix/cyclone/blob/66e3e4fb4dad78a319478b3a20d91a94f2439557/cyclone/httpserver.py#L56) should extend [`t.p.b.LineReceiver`](https://twistedmatrix.com/documents/current/api/twisted.protocols.basic.LineReceiver.html) instead of [`t.w.h.HTTPChannel`](https://twistedmatrix.com/documents/current/api/twisted.web.http.HTTPChannel.html) (which itself extends `t.p.b.LineReceiver`, but supports all kinds of goodies like timeouts, etc.)?

**Comment by fiorix** [comment]
No particular reason. Either it didn't exist by the time I first wrote this code back in 2009, or I didn't know about its existence. If you think it's worth a try, patches are always welcome.

**Comment by mbogosian** [comment]
Thanks! :bow:

**Comment by dpnova** [comment]
My 2c here as well... cyclone outperforms twisted.web by a significant margin. One of the great advantages of cyclone is that it's not tied so tightly to the http stack in twisted... if we were to use HTTPChannel I'd want to see how it impacted performance too!
