### ISSUE TITLE
FIXED IN #170 - JsonrpcRequestHandler returns Content-Type: text/html instead of application/json

### ISSUE THREAD

**Issue by posita** [fiorix/cyclone#169]
```sh
% curl --verbose -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST --data [JSONRPC_DATA] [JSONRPC_URL]
...
< Content-Type: text/html; charset=UTF-8
...
```

**Comment by fiorix** [comment]
Are you sure you're hitting the correct handler? That seems a bit odd although I haven't touched that code in years. If you find it as a bug, please submit a PR and I'll review it.

**Comment by posita** [comment]
> Are you sure you're hitting the correct handler?

I believe so. I'm getting a JSON-RPC response from my subclass of `JsonrpcRequestHandler`. The only thing that's weird is the `Content-Type`.

> That seems a bit odd although I haven't touched that code in years. If you find it as a bug, please submit a PR and I'll review it.

See #170, which fixes my issue (leading me to believe it's hitting the correct handler). There is nothing I see in [`jsonrpc.py`](https://github.com/fiorix/cyclone/blob/73f1a7c87769a037e976f4b6156889090c32fd18/cyclone/jsonrpc.py) (before my patch) that looks like it addresses content types. Searching for ["application json"](https://github.com/fiorix/cyclone/search?q=application+json&type=Code&utf8=%E2%9C%93) in the repository doesn't yield any code results (although I wouldn't consider that exhaustive).
