### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by greentornado** [fiorix/cyclone#175]
Hi I used this
```
application = cyclone.web.Application([
        (r"/", MainHandler),
        (r"/story/([0-9]+)", StoryHandler)
    ],debug=True)
```

But the app is not reloading when code changes :D

**Comment by dpnova** [comment]
Hi, did you read somewhere that it was supposed to do that? Perhaps this will be of help?

**Comment by greentornado** [comment]
;) Thank you
