### ISSUE TITLE
Future of cyclone: twisted adoption, outstanding issues etc

### ISSUE THREAD

**Issue by dpnova** [fiorix/cyclone#177]
This is a place holder for the discussion about the future of cyclone, potentially as a member project of @twisted. This conversation started here: https://github.com/fiorix/cyclone/issues/168

I will document my understanding of the project as it stands right now, so we can have an open conversation about what approach we will take.

Some things I think are worth noting (I'll add details when I get some time):
- python 3: https://github.com/fiorix/cyclone/issues/171
- pypi release: https://github.com/fiorix/cyclone/issues/168
- test coverage
- review/acceptance guidelines
- use of logging (style, libraries etc)
- maintaining feature parity with the mainline Tornado project
- contributors
- oversight from the twisted mother ship

Please add anything you feel is relevant! Ultimately I feel that cyclone fills a tornado-esqe hole in the things you can do with twisted that I feel is compatible with klein and t.w. The beauty of twisted is we can use all these things together :)

Cheers

**Comment by vltr** [comment]
great, @dpnova !

my personal opinion is kind of resilient about feature parity with tornado, but that's another discussion. as for everything else, I agree if there's what it takes to continue this project. i can contribute :+1:

**Comment by biggers** [comment]
Any further word on this Issue?   Even if folks just dropped their "ports" or patches (for any part of the above punch-list) as Pulls, that could help a lot towards getting Cyclone updated.  Thanks to @fiorix for the original work, @dpnova  for pushing it forward, and all the contributors.   Cyclone is good stuff.

**Comment by fiorix** [comment]
There's definitely a niche for this, especially if it can provide a smooth transition for running existing code on py3.

**Comment by dpnova** [comment]
I've updated my original comment. I think we should go for python3 first. This will the warrant a release to pypi.

**Comment by dpnova** [comment]
One other thing to note from me is I'm not working at scrunch anymore, which is where I was dealing with cyclone very regularly.

**Comment by vltr** [comment]
@dpnova me too. I had to move forward, personally 😞

**Comment by fiorix** [comment]
Closing this as we've recently released the python3 version thanks to @waghanza. There's still documentation to update (and the content in cyclone.io) but will deal with that separate.
