### ISSUE TITLE
Sendmail SSL handshake fails with SSLv3_METHOD

### ISSUE THREAD

**Issue by frmdstryr** [fiorix/cyclone#182]
I'm trying to send an email with AWS's SES SMTP server but getting the following error:
```
	Traceback (most recent call last):
	Failure: twisted.mail._except.SMTPTLSError: 451 Could not complete the SSL/TLS handshake
	<<< 250-AUTH PLAIN LOGIN
	<<< 250 Ok
	>>> STARTTLS
	<<< 220 Ready to start TLS
```

due to:

`OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_new', 'null ssl method passed')]`

Versions:
```python
cryptography==1.8.1
cyclone==1.1
pyOpenSSL==16.2.0
tornado==4.4.3
Twisted==17.1.0

```

Config:

```python
mail.sendmail(dict(
    host="email-smtp.us-east-1.amazonaws.com",
    username="username",
    password="password",
    port=587,  # 25, 465 or 587
    tls=True
),msg)

```
I can see cyclone is setting it to `SSLv3_METHOD` it works if I modify it to use `TLSv1_METHOD`.

Any ideas why SSLv3 is not working?

**Comment by dpnova** [comment]
hey is this using cyclone from pypi? I think some of this has been updated in master in this github repo.

**Comment by frmdstryr** [comment]
Yeah, pypi via dokku. I'll try the git master and see if that works.

**Comment by ygl-rg** [comment]
Does it work?

**Comment by frmdstryr** [comment]
Never got to test this.
