### ISSUE TITLE
No module cStringIO

### ISSUE THREAD

**Issue by waghanza** [fiorix/cyclone#183]
Hi,

Following #173, it appears that a `python2` **module** is still imported 

https://github.com/fiorix/cyclone/blob/de77ab5ed2dd685079bd76828ea917eca2f5f6fa/cyclone/template.py#L200

A possible workaround could be to load a `python3` alternative, but this drop support to `python2`.

@fiorix What do you think ?

We are challenging `cyclone` here => https://github.com/the-benchmarker/web-frameworks/pull/396

Regards,

**Comment by fiorix** [comment]
That's fine, I just merged. Thanks!

**Comment by waghanza** [comment]
Thanks @fiorix. Do you plan to publish `cyclone` with this **patch** ?

**Comment by fiorix** [comment]
Oh, shit. I haven't used PyPI in a while and they keep changing things. Will come back to this whenever I find time.

**Comment by waghanza** [comment]
Sure, if you want help (auto-deployment Aka CI/CD is great for saving time)

CI could push on pypi when a github release is made :tada:

**Comment by fiorix** [comment]
Today I found that cStringIO is still present in a test file: https://github.com/fiorix/cyclone/blob/master/cyclone/tests/test_httpclient.py#L19

Also found that various tests hang in Python 3 while they all pass in Python 2.

This is probably outstanding work related to #177.

**Comment by waghanza** [comment]
Yeah, there is probably some python 3 tests failures. I honestly have work on this only because `cyclone` fails on a project I have.

I think, however, activate CI will be a great benefits  for `cyclone` **community** port to py3 😃
